---
- name: system_tweaks | Setting kvm_sysctl_settings
  become: true
  sysctl:
    name: "{{ item['name'] }}"
    value: "{{ item['value'] }}"
    state: "{{ item['state'] }}"
    reload: true
  loop: "{{ kvm_sysctl_settings }}"
